blank_issues_enabled: false
contact_links:
  - name: Questions or Discussions
    url: https://github.com/beimnettes/influencer-manager/discussions
    about: Please use Discussions for questions or ideas.
